# Generated by Django 3.1 on 2020-08-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AugustUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code_user', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.augustuser')),
            ],
        ),
        migrations.AddField(
            model_name='augustuser',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='_augustuser_references_+', through='signup.Referral', to='signup.AugustUser'),
        ),
    ]
