# Generated by Django 3.1 on 2020-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='augustuser',
            name='references',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.ManyToManyField(blank=True, to='signup.AugustUser'),
        ),
    ]
