# Generated by Django 3.1 on 2020-08-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='augustuser',
            old_name='referral_code_user',
            new_name='referral_code_used',
        ),
    ]
