# Generated by Django 3.1 on 2020-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200816_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
